//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.10 at 01:28:15 PM EST 
//


package com.xeroobjects.xero;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.xeroobjects.xero package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Accounts_QNAME = new QName("", "Accounts");
    private final static QName _CreditNotes_QNAME = new QName("", "CreditNotes");
    private final static QName _TrackingCategories_QNAME = new QName("", "TrackingCategories");
    private final static QName _Invoices_QNAME = new QName("", "Invoices");
    private final static QName _Contacts_QNAME = new QName("", "Contacts");
    private final static QName _LineItems_QNAME = new QName("", "LineItems");
    private final static QName _Payments_QNAME = new QName("", "Payments");
    private final static QName _OnlineInvoices_QNAME = new QName("", "OnlineInvoices");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.xeroobjects.xero
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ArrayOfAccount }
     * 
     */
    public ArrayOfAccount createArrayOfAccount() {
        return new ArrayOfAccount();
    }

    /**
     * Create an instance of {@link ArrayOfCreditNote }
     * 
     */
    public ArrayOfCreditNote createArrayOfCreditNote() {
        return new ArrayOfCreditNote();
    }

    /**
     * Create an instance of {@link ArrayOfInvoice }
     * 
     */
    public ArrayOfInvoice createArrayOfInvoice() {
        return new ArrayOfInvoice();
    }

    /**
     * Create an instance of {@link ArrayOfTrackingCategory }
     * 
     */
    public ArrayOfTrackingCategory createArrayOfTrackingCategory() {
        return new ArrayOfTrackingCategory();
    }

    /**
     * Create an instance of {@link ArrayOfContact }
     * 
     */
    public ArrayOfContact createArrayOfContact() {
        return new ArrayOfContact();
    }

    /**
     * Create an instance of {@link ArrayOfLineItem }
     * 
     */
    public ArrayOfLineItem createArrayOfLineItem() {
        return new ArrayOfLineItem();
    }

    /**
     * Create an instance of {@link ArrayOfPayment }
     * 
     */
    public ArrayOfPayment createArrayOfPayment() {
        return new ArrayOfPayment();
    }

    /**
     * Create an instance of {@link CreditNote }
     * 
     */
    public CreditNote createCreditNote() {
        return new CreditNote();
    }

    /**
     * Create an instance of {@link ArrayOfAddress }
     * 
     */
    public ArrayOfAddress createArrayOfAddress() {
        return new ArrayOfAddress();
    }

    /**
     * Create an instance of {@link ArrayOfPhone }
     * 
     */
    public ArrayOfPhone createArrayOfPhone() {
        return new ArrayOfPhone();
    }

    /**
     * Create an instance of {@link TrackingCategoryOption }
     * 
     */
    public TrackingCategoryOption createTrackingCategoryOption() {
        return new TrackingCategoryOption();
    }

    /**
     * Create an instance of {@link Payment }
     * 
     */
    public Payment createPayment() {
        return new Payment();
    }

    /**
     * Create an instance of {@link ArrayOfWarning }
     * 
     */
    public ArrayOfWarning createArrayOfWarning() {
        return new ArrayOfWarning();
    }

    /**
     * Create an instance of {@link ArrayOfContactGroup }
     * 
     */
    public ArrayOfContactGroup createArrayOfContactGroup() {
        return new ArrayOfContactGroup();
    }

    /**
     * Create an instance of {@link TrackingCategory }
     * 
     */
    public TrackingCategory createTrackingCategory() {
        return new TrackingCategory();
    }

    /**
     * Create an instance of {@link ArrayOfTrackingCategoryOption }
     * 
     */
    public ArrayOfTrackingCategoryOption createArrayOfTrackingCategoryOption() {
        return new ArrayOfTrackingCategoryOption();
    }

    /**
     * Create an instance of {@link Invoice }
     * 
     */
    public Invoice createInvoice() {
        return new Invoice();
    }

    /**
     * Create an instance of {@link ArrayOfValidationError }
     * 
     */
    public ArrayOfValidationError createArrayOfValidationError() {
        return new ArrayOfValidationError();
    }

    /**
     * Create an instance of {@link Phone }
     * 
     */
    public Phone createPhone() {
        return new Phone();
    }

    /**
     * Create an instance of {@link Account }
     * 
     */
    public Account createAccount() {
        return new Account();
    }

    /**
     * Create an instance of {@link Warning }
     * 
     */
    public Warning createWarning() {
        return new Warning();
    }

    /**
     * Create an instance of {@link Hyperlink }
     * 
     */
    public Hyperlink createHyperlink() {
        return new Hyperlink();
    }

    /**
     * Create an instance of {@link Contact }
     * 
     */
    public Contact createContact() {
        return new Contact();
    }

    /**
     * Create an instance of {@link ValidationError }
     * 
     */
    public ValidationError createValidationError() {
        return new ValidationError();
    }

    /**
     * Create an instance of {@link ContactGroup }
     * 
     */
    public ContactGroup createContactGroup() {
        return new ContactGroup();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link LineItem }
     * 
     */
    public LineItem createLineItem() {
        return new LineItem();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfAccount }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Accounts")
    public JAXBElement<ArrayOfAccount> createAccounts(ArrayOfAccount value) {
        return new JAXBElement<ArrayOfAccount>(_Accounts_QNAME, ArrayOfAccount.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfCreditNote }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CreditNotes")
    public JAXBElement<ArrayOfCreditNote> createCreditNotes(ArrayOfCreditNote value) {
        return new JAXBElement<ArrayOfCreditNote>(_CreditNotes_QNAME, ArrayOfCreditNote.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfTrackingCategory }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TrackingCategories")
    public JAXBElement<ArrayOfTrackingCategory> createTrackingCategories(ArrayOfTrackingCategory value) {
        return new JAXBElement<ArrayOfTrackingCategory>(_TrackingCategories_QNAME, ArrayOfTrackingCategory.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfInvoice }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Invoices")
    public JAXBElement<ArrayOfInvoice> createInvoices(ArrayOfInvoice value) {
        return new JAXBElement<ArrayOfInvoice>(_Invoices_QNAME, ArrayOfInvoice.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfContact }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Contacts")
    public JAXBElement<ArrayOfContact> createContacts(ArrayOfContact value) {
        return new JAXBElement<ArrayOfContact>(_Contacts_QNAME, ArrayOfContact.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfLineItem }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LineItems")
    public JAXBElement<ArrayOfLineItem> createLineItems(ArrayOfLineItem value) {
        return new JAXBElement<ArrayOfLineItem>(_LineItems_QNAME, ArrayOfLineItem.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfPayment }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Payments")
    public JAXBElement<ArrayOfPayment> createPayments(ArrayOfPayment value) {
        return new JAXBElement<ArrayOfPayment>(_Payments_QNAME, ArrayOfPayment.class, null, value);
    }
    
    @XmlElementDecl(namespace = "", name = "OnlineInvoices")
    public JAXBElement<OnlineInvoice> createOnlineInvoices(OnlineInvoice value) {
        return new JAXBElement<OnlineInvoice>(_OnlineInvoices_QNAME, OnlineInvoice.class, null, value);
    }

}
